pipeline {
    agent any
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Build using the serverlesss_deploy-master folder as context
                    dockerImage = docker.build('portfolio-app', 'serverlesss_deploy-master')
                }
            }
        }
        stage('Push Image') {
            steps {
                withDockerRegistry([credentialsId: 'dockerhub-creds', url: '']) {
                    dockerImage.push('latest')
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                sh 'kubectl apply -f serverlesss_deploy-master/k8s-deployment.yaml'
            }
        }
    }
}
